// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_full_n,
        imgRgb_write,
        pixWindow_val_val_V_79_i,
        pixWindow_val_val_V_78_i,
        pixWindow_val_val_V_77_i,
        pixWindow_val_val_V_76_i,
        pixWindow_val_val_V_75_i,
        pixWindow_val_val_V_74_i,
        pixWindow_val_val_V_73_i,
        pixWindow_val_val_V_72_i,
        pixWindow_val_val_V_71_i,
        pixWindow_val_val_V_70_i,
        pixWindow_val_val_V_69_i,
        pixWindow_val_val_V_i,
        add_ln833_i,
        x_phase_i,
        xor_i,
        out_y_i,
        lineBuffer_val_V_2_i_address0,
        lineBuffer_val_V_2_i_ce0,
        lineBuffer_val_V_2_i_we0,
        lineBuffer_val_V_2_i_d0,
        lineBuffer_val_V_2_i_address1,
        lineBuffer_val_V_2_i_ce1,
        lineBuffer_val_V_2_i_q1,
        lineBuffer_val_V_i_address0,
        lineBuffer_val_V_i_ce0,
        lineBuffer_val_V_i_we0,
        lineBuffer_val_V_i_d0,
        lineBuffer_val_V_i_address1,
        lineBuffer_val_V_i_ce1,
        lineBuffer_val_V_i_q1,
        trunc_ln,
        cmp204_i,
        cmp60_i,
        pixWindow_val_val_V_91_i_out,
        pixWindow_val_val_V_91_i_out_ap_vld,
        pixWindow_val_val_V_90_i_out,
        pixWindow_val_val_V_90_i_out_ap_vld,
        pixWindow_val_val_V_89_i_out,
        pixWindow_val_val_V_89_i_out_ap_vld,
        pixWindow_val_val_V_88_i_out,
        pixWindow_val_val_V_88_i_out_ap_vld,
        pixWindow_val_val_V_87_i_out,
        pixWindow_val_val_V_87_i_out_ap_vld,
        pixWindow_val_val_V_86_i_out,
        pixWindow_val_val_V_86_i_out_ap_vld,
        pixWindow_val_val_V_85_i_out,
        pixWindow_val_val_V_85_i_out_ap_vld,
        pixWindow_val_val_V_84_i_out,
        pixWindow_val_val_V_84_i_out_ap_vld,
        pixWindow_val_val_V_83_i_out,
        pixWindow_val_val_V_83_i_out_ap_vld,
        pixWindow_val_val_V_82_i_out,
        pixWindow_val_val_V_82_i_out_ap_vld,
        pixWindow_val_val_V_81_i_out,
        pixWindow_val_val_V_81_i_out_ap_vld,
        pixWindow_val_val_V_80_i_out,
        pixWindow_val_val_V_80_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] imgRB_dout;
input  [1:0] imgRB_num_data_valid;
input  [1:0] imgRB_fifo_cap;
input   imgRB_empty_n;
output   imgRB_read;
output  [29:0] imgRgb_din;
input  [1:0] imgRgb_num_data_valid;
input  [1:0] imgRgb_fifo_cap;
input   imgRgb_full_n;
output   imgRgb_write;
input  [9:0] pixWindow_val_val_V_79_i;
input  [9:0] pixWindow_val_val_V_78_i;
input  [9:0] pixWindow_val_val_V_77_i;
input  [9:0] pixWindow_val_val_V_76_i;
input  [9:0] pixWindow_val_val_V_75_i;
input  [9:0] pixWindow_val_val_V_74_i;
input  [9:0] pixWindow_val_val_V_73_i;
input  [9:0] pixWindow_val_val_V_72_i;
input  [9:0] pixWindow_val_val_V_71_i;
input  [9:0] pixWindow_val_val_V_70_i;
input  [9:0] pixWindow_val_val_V_69_i;
input  [9:0] pixWindow_val_val_V_i;
input  [10:0] add_ln833_i;
input  [0:0] x_phase_i;
input  [14:0] xor_i;
input  [11:0] out_y_i;
output  [10:0] lineBuffer_val_V_2_i_address0;
output   lineBuffer_val_V_2_i_ce0;
output   lineBuffer_val_V_2_i_we0;
output  [29:0] lineBuffer_val_V_2_i_d0;
output  [10:0] lineBuffer_val_V_2_i_address1;
output   lineBuffer_val_V_2_i_ce1;
input  [29:0] lineBuffer_val_V_2_i_q1;
output  [10:0] lineBuffer_val_V_i_address0;
output   lineBuffer_val_V_i_ce0;
output   lineBuffer_val_V_i_we0;
output  [29:0] lineBuffer_val_V_i_d0;
output  [10:0] lineBuffer_val_V_i_address1;
output   lineBuffer_val_V_i_ce1;
input  [29:0] lineBuffer_val_V_i_q1;
input  [10:0] trunc_ln;
input  [0:0] cmp204_i;
input  [0:0] cmp60_i;
output  [9:0] pixWindow_val_val_V_91_i_out;
output   pixWindow_val_val_V_91_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_90_i_out;
output   pixWindow_val_val_V_90_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_89_i_out;
output   pixWindow_val_val_V_89_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_88_i_out;
output   pixWindow_val_val_V_88_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_87_i_out;
output   pixWindow_val_val_V_87_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_86_i_out;
output   pixWindow_val_val_V_86_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_85_i_out;
output   pixWindow_val_val_V_85_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_84_i_out;
output   pixWindow_val_val_V_84_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_83_i_out;
output   pixWindow_val_val_V_83_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_82_i_out;
output   pixWindow_val_val_V_82_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_81_i_out;
output   pixWindow_val_val_V_81_i_out_ap_vld;
output  [9:0] pixWindow_val_val_V_80_i_out;
output   pixWindow_val_val_V_80_i_out_ap_vld;

reg ap_idle;
reg imgRB_read;
reg imgRgb_write;
reg lineBuffer_val_V_2_i_ce0;
reg lineBuffer_val_V_2_i_we0;
reg lineBuffer_val_V_2_i_ce1;
reg lineBuffer_val_V_i_ce0;
reg lineBuffer_val_V_i_we0;
reg lineBuffer_val_V_i_ce1;
reg pixWindow_val_val_V_91_i_out_ap_vld;
reg pixWindow_val_val_V_90_i_out_ap_vld;
reg pixWindow_val_val_V_89_i_out_ap_vld;
reg pixWindow_val_val_V_88_i_out_ap_vld;
reg pixWindow_val_val_V_87_i_out_ap_vld;
reg pixWindow_val_val_V_86_i_out_ap_vld;
reg pixWindow_val_val_V_85_i_out_ap_vld;
reg pixWindow_val_val_V_84_i_out_ap_vld;
reg pixWindow_val_val_V_83_i_out_ap_vld;
reg pixWindow_val_val_V_82_i_out_ap_vld;
reg pixWindow_val_val_V_81_i_out_ap_vld;
reg pixWindow_val_val_V_80_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln836_reg_1933;
reg   [0:0] icmp_ln846_reg_1937;
wire   [0:0] cmp60_i_read_reg_1922;
reg    ap_predicate_op84_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
reg   [0:0] tmp_25_reg_1976;
reg   [0:0] tmp_25_reg_1976_pp0_iter4_reg;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln836_fu_577_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRB_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRgb_blk_n;
reg   [9:0] pixWindow_val_val_V_138_reg_421;
reg   [9:0] pixWindow_val_val_V_138_reg_421_pp0_iter3_reg;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] pixWindow_val_val_V_138_reg_421_pp0_iter4_reg;
reg   [9:0] pixWindow_val_val_V_137_reg_431;
reg   [9:0] pixWindow_val_val_V_137_reg_431_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_137_reg_431_pp0_iter4_reg;
reg   [9:0] pixWindow_val_val_V_136_reg_441;
reg   [9:0] pixWindow_val_val_V_136_reg_441_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_136_reg_441_pp0_iter4_reg;
reg   [0:0] icmp_ln836_reg_1933_pp0_iter1_reg;
reg   [0:0] icmp_ln836_reg_1933_pp0_iter2_reg;
reg   [0:0] icmp_ln836_reg_1933_pp0_iter3_reg;
wire   [0:0] icmp_ln846_fu_605_p2;
reg   [0:0] icmp_ln846_reg_1937_pp0_iter1_reg;
reg   [10:0] lineBuffer_val_V_i_addr_reg_1941;
reg   [10:0] lineBuffer_val_V_2_i_addr_reg_1947;
reg   [10:0] lineBuffer_val_V_2_i_addr_reg_1947_pp0_iter1_reg;
wire   [0:0] cmp162_i_fu_611_p2;
reg   [0:0] cmp162_i_reg_1953;
reg   [0:0] cmp162_i_reg_1953_pp0_iter1_reg;
wire   [0:0] icmp_ln969_fu_633_p2;
reg   [0:0] icmp_ln969_reg_1969;
reg   [0:0] icmp_ln969_reg_1969_pp0_iter1_reg;
reg   [0:0] icmp_ln969_reg_1969_pp0_iter2_reg;
reg   [0:0] icmp_ln969_reg_1969_pp0_iter3_reg;
reg   [0:0] icmp_ln969_reg_1969_pp0_iter4_reg;
reg   [0:0] tmp_25_reg_1976_pp0_iter1_reg;
reg   [0:0] tmp_25_reg_1976_pp0_iter2_reg;
reg   [0:0] tmp_25_reg_1976_pp0_iter3_reg;
wire   [9:0] trunc_ln628_fu_658_p1;
reg   [9:0] trunc_ln628_reg_1980;
reg   [9:0] tmp_i_reg_1989;
reg   [9:0] tmp_2_i_reg_1998;
wire   [9:0] trunc_ln868_fu_682_p1;
reg   [9:0] pixWindow_val_val_V_94_reg_2022;
reg   [9:0] pixWindow_val_val_V_94_reg_2022_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_95_reg_2027;
reg   [9:0] pixWindow_val_val_V_95_reg_2027_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_96_reg_2032;
reg   [9:0] pixWindow_val_val_V_96_reg_2032_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_100_reg_2037;
reg   [9:0] pixWindow_val_val_V_100_reg_2037_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_101_reg_2042;
reg   [9:0] pixWindow_val_val_V_101_reg_2042_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_102_reg_2047;
reg   [9:0] pixWindow_val_val_V_102_reg_2047_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_103_reg_2052;
reg   [9:0] pixWindow_val_val_V_103_reg_2052_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_104_reg_2057;
reg   [9:0] pixWindow_val_val_V_104_reg_2057_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_105_reg_2062;
reg   [9:0] pixWindow_val_val_V_105_reg_2062_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_97_reg_2067;
reg   [9:0] pixWindow_val_val_V_97_reg_2067_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_98_reg_2073;
reg   [9:0] pixWindow_val_val_V_98_reg_2073_pp0_iter3_reg;
reg   [9:0] pixWindow_val_val_V_99_reg_2079;
reg   [9:0] pixWindow_val_val_V_99_reg_2079_pp0_iter3_reg;
wire   [9:0] pixWindow_val_val_V_111_fu_796_p3;
wire   [9:0] pixWindow_val_val_V_110_fu_802_p3;
wire   [9:0] pixWindow_val_val_V_109_fu_808_p3;
wire   [10:0] zext_ln1496_11_fu_933_p1;
reg   [10:0] zext_ln1496_11_reg_2100;
wire   [10:0] zext_ln1496_12_fu_937_p1;
reg   [10:0] zext_ln1496_12_reg_2105;
wire   [10:0] zext_ln1496_15_fu_941_p1;
reg   [10:0] zext_ln1496_15_reg_2110;
wire   [10:0] zext_ln1496_16_fu_945_p1;
reg   [10:0] zext_ln1496_16_reg_2115;
wire   [10:0] ret_V_31_fu_957_p2;
reg   [10:0] ret_V_31_reg_2120;
reg   [10:0] ret_V_31_reg_2120_pp0_iter3_reg;
wire   [9:0] trunc_ln61_8_fu_963_p1;
reg   [9:0] trunc_ln61_8_reg_2125;
reg   [9:0] trunc_ln61_8_reg_2125_pp0_iter3_reg;
wire   [10:0] ret_V_60_fu_967_p2;
reg   [10:0] ret_V_60_reg_2131;
wire   [10:0] ret_V_61_fu_973_p2;
reg   [10:0] ret_V_61_reg_2136;
wire   [10:0] ret_V_62_fu_979_p2;
reg   [10:0] ret_V_62_reg_2141;
wire   [10:0] ret_V_63_fu_985_p2;
reg   [10:0] ret_V_63_reg_2146;
wire   [10:0] ret_V_30_fu_1163_p2;
reg   [10:0] ret_V_30_reg_2151;
wire   [9:0] trunc_ln61_7_fu_1169_p1;
reg   [9:0] trunc_ln61_7_reg_2156;
wire   [9:0] sub_ln61_7_fu_1173_p2;
reg   [9:0] sub_ln61_7_reg_2161;
wire   [9:0] sub_ln61_8_fu_1179_p2;
reg   [9:0] sub_ln61_8_reg_2166;
wire   [10:0] ret_V_54_fu_1192_p2;
reg   [10:0] ret_V_54_reg_2171;
wire   [10:0] ret_V_55_fu_1206_p2;
reg   [10:0] ret_V_55_reg_2176;
wire   [11:0] ret_V_38_fu_1232_p2;
reg   [11:0] ret_V_38_reg_2181;
wire   [11:0] ret_V_42_fu_1258_p2;
reg   [11:0] ret_V_42_reg_2188;
wire   [12:0] ret_V_47_fu_1332_p3;
reg   [12:0] ret_V_47_reg_2195;
wire   [12:0] ret_V_51_fu_1408_p3;
reg   [12:0] ret_V_51_reg_2200;
wire   [13:0] ret_V_64_fu_1611_p2;
reg   [13:0] ret_V_64_reg_2205;
wire   [13:0] ret_V_65_fu_1628_p2;
reg   [13:0] ret_V_65_reg_2210;
reg   [0:0] tmp_21_reg_2215;
reg   [3:0] tmp_22_reg_2221;
reg   [3:0] tmp_24_reg_2226;
wire   [0:0] and_ln998_fu_1675_p2;
reg   [0:0] and_ln998_reg_2231;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01244_22367_ph_i_reg_367;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01244_22367_ph_i_reg_367;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01245_22365_ph_i_reg_376;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01245_22365_ph_i_reg_376;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01246_22363_ph_i_reg_385;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01246_22363_ph_i_reg_385;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_141_phi_fu_397_p4;
wire   [9:0] pixWindow_val_val_V_117_fu_838_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_141_reg_394;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_140_phi_fu_406_p4;
wire   [9:0] pixWindow_val_val_V_116_fu_846_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_140_reg_403;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_139_phi_fu_415_p4;
wire   [9:0] pixWindow_val_val_V_115_fu_854_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_139_reg_412;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_138_phi_fu_424_p4;
wire   [9:0] pixWindow_val_val_V_114_fu_775_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_138_reg_421;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_137_phi_fu_434_p4;
wire   [9:0] pixWindow_val_val_V_113_fu_782_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_137_reg_431;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_136_phi_fu_444_p4;
wire   [9:0] pixWindow_val_val_V_112_fu_789_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_136_reg_441;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_132_phi_fu_454_p4;
wire   [9:0] pixWindow_val_val_V_108_fu_814_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_132_reg_451;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_131_phi_fu_463_p4;
wire   [9:0] pixWindow_val_val_V_107_fu_822_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_131_reg_460;
reg   [9:0] ap_phi_mux_pixWindow_val_val_V_130_phi_fu_472_p4;
wire   [9:0] pixWindow_val_val_V_106_fu_830_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_130_reg_469;
wire   [9:0] ap_phi_reg_pp0_iter0_pixWindow_val_val_V_135_reg_478;
reg   [9:0] ap_phi_reg_pp0_iter1_pixWindow_val_val_V_135_reg_478;
reg   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_135_reg_478;
reg   [9:0] ap_phi_reg_pp0_iter3_pixWindow_val_val_V_135_reg_478;
wire   [9:0] ap_phi_reg_pp0_iter0_pixWindow_val_val_V_134_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter1_pixWindow_val_val_V_134_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_134_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter3_pixWindow_val_val_V_134_reg_487;
wire   [9:0] ap_phi_reg_pp0_iter0_pixWindow_val_val_V_133_reg_496;
reg   [9:0] ap_phi_reg_pp0_iter1_pixWindow_val_val_V_133_reg_496;
reg   [9:0] ap_phi_reg_pp0_iter2_pixWindow_val_val_V_133_reg_496;
reg   [9:0] ap_phi_reg_pp0_iter3_pixWindow_val_val_V_133_reg_496;
wire   [63:0] zext_ln836_1_fu_589_p1;
reg   [10:0] x_fu_154;
wire   [10:0] x_8_fu_583_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [9:0] pixWindow_val_val_V_fu_158;
wire   [9:0] trunc_ln628_2_fu_751_p1;
reg   [9:0] pixWindow_val_val_V_83_fu_162;
wire   [9:0] tmp_4_i_fu_755_p4;
reg   [9:0] pixWindow_val_val_V_84_fu_166;
wire   [9:0] tmp_5_i_fu_765_p4;
reg   [9:0] pixWindow_val_val_V_85_fu_170;
reg   [9:0] pixWindow_val_val_V_86_fu_174;
reg   [9:0] pixWindow_val_val_V_87_fu_178;
reg   [9:0] pixWindow_val_val_V_88_fu_182;
reg   [9:0] pixWindow_val_val_V_89_fu_186;
reg   [9:0] pixWindow_val_val_V_90_fu_190;
reg   [9:0] pixWindow_val_val_V_91_fu_194;
reg   [9:0] pixWindow_val_val_V_92_fu_198;
reg   [9:0] pixWindow_val_val_V_93_fu_202;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] zext_ln836_fu_573_p1;
wire   [0:0] trunc_ln844_fu_595_p1;
wire   [0:0] xor_ln969_fu_617_p2;
wire   [0:0] xor_ln969_1_fu_623_p2;
wire   [14:0] zext_ln969_fu_629_p1;
wire   [11:0] out_x_fu_599_p2;
wire   [11:0] or_ln1007_fu_639_p2;
wire   [9:0] PixBufVal_val_V_4_fu_862_p3;
wire   [9:0] PixBufVal_val_V_3_fu_868_p3;
wire   [9:0] PixBufVal_val_V_fu_874_p3;
wire   [10:0] zext_ln1496_19_fu_949_p1;
wire   [10:0] zext_ln1496_20_fu_953_p1;
wire   [10:0] zext_ln1496_fu_1015_p1;
wire   [10:0] zext_ln1496_10_fu_1019_p1;
wire   [10:0] ret_V_fu_1023_p2;
wire   [9:0] trunc_ln61_fu_1029_p1;
wire   [0:0] tmp_fu_1039_p3;
wire   [9:0] sub_ln61_fu_1033_p2;
wire   [10:0] ret_V_27_fu_1055_p2;
wire   [9:0] trunc_ln61_4_fu_1059_p1;
wire   [0:0] tmp_12_fu_1069_p3;
wire   [9:0] sub_ln61_4_fu_1063_p2;
wire   [10:0] zext_ln1496_13_fu_1085_p1;
wire   [10:0] zext_ln1496_14_fu_1089_p1;
wire   [10:0] ret_V_28_fu_1093_p2;
wire   [9:0] trunc_ln61_5_fu_1099_p1;
wire   [0:0] tmp_13_fu_1109_p3;
wire   [9:0] sub_ln61_5_fu_1103_p2;
wire   [10:0] ret_V_29_fu_1125_p2;
wire   [9:0] trunc_ln61_6_fu_1129_p1;
wire   [0:0] tmp_14_fu_1139_p3;
wire   [9:0] sub_ln61_6_fu_1133_p2;
wire   [10:0] zext_ln1496_17_fu_1155_p1;
wire   [10:0] zext_ln1496_18_fu_1159_p1;
wire   [9:0] DRh_V_fu_1047_p3;
wire   [9:0] DGh_V_fu_1117_p3;
wire   [10:0] zext_ln186_fu_1184_p1;
wire   [10:0] zext_ln186_1_fu_1188_p1;
wire   [9:0] DRv_V_fu_1077_p3;
wire   [9:0] DGv_V_fu_1147_p3;
wire   [10:0] zext_ln186_4_fu_1198_p1;
wire   [10:0] zext_ln186_5_fu_1202_p1;
wire   [10:0] ret_V_56_fu_1212_p2;
wire   [10:0] ret_V_57_fu_1218_p2;
wire  signed [11:0] sext_ln186_fu_1224_p1;
wire  signed [11:0] sext_ln186_1_fu_1228_p1;
wire   [10:0] ret_V_58_fu_1238_p2;
wire   [10:0] ret_V_59_fu_1244_p2;
wire  signed [11:0] sext_ln186_2_fu_1250_p1;
wire  signed [11:0] sext_ln186_3_fu_1254_p1;
wire  signed [11:0] sext_ln186_4_fu_1264_p1;
wire  signed [11:0] sext_ln186_5_fu_1267_p1;
wire   [11:0] ret_V_46_fu_1270_p2;
wire   [11:0] sub_ln1513_5_fu_1284_p2;
wire   [10:0] trunc_ln1513_2_i_fu_1290_p4;
wire  signed [11:0] sext_ln1513_4_fu_1300_p1;
wire   [12:0] zext_ln1513_4_fu_1304_p1;
wire   [10:0] trunc_ln1513_7_i_fu_1314_p4;
wire  signed [11:0] sext_ln1513_5_fu_1324_p1;
wire   [0:0] tmp_19_fu_1276_p3;
wire   [12:0] sub_ln1513_6_fu_1308_p2;
wire   [12:0] zext_ln1513_5_fu_1328_p1;
wire  signed [11:0] sext_ln186_6_fu_1340_p1;
wire  signed [11:0] sext_ln186_7_fu_1343_p1;
wire   [11:0] ret_V_50_fu_1346_p2;
wire   [11:0] sub_ln1513_7_fu_1360_p2;
wire   [10:0] trunc_ln1513_10_i_fu_1366_p4;
wire  signed [11:0] sext_ln1513_6_fu_1376_p1;
wire   [12:0] zext_ln1513_6_fu_1380_p1;
wire   [10:0] trunc_ln1513_9_i_fu_1390_p4;
wire  signed [11:0] sext_ln1513_7_fu_1400_p1;
wire   [0:0] tmp_20_fu_1352_p3;
wire   [12:0] sub_ln1513_8_fu_1384_p2;
wire   [12:0] zext_ln1513_7_fu_1404_p1;
wire   [0:0] tmp_15_fu_1416_p3;
wire   [0:0] tmp_16_fu_1429_p3;
wire   [9:0] DBh_V_fu_1423_p3;
wire   [11:0] zext_ln186_2_fu_1442_p1;
wire   [11:0] zext_ln186_3_fu_1445_p1;
wire   [9:0] DBv_V_fu_1436_p3;
wire   [11:0] zext_ln186_6_fu_1455_p1;
wire   [11:0] zext_ln186_7_fu_1458_p1;
wire   [11:0] ret_V_33_fu_1449_p2;
wire   [11:0] ret_V_35_fu_1462_p2;
wire   [11:0] sub_ln1513_fu_1481_p2;
wire   [10:0] trunc_ln1513_i_fu_1486_p4;
wire  signed [11:0] sext_ln1513_fu_1496_p1;
wire   [12:0] zext_ln1513_fu_1500_p1;
wire   [10:0] trunc_ln1513_3_i_fu_1510_p4;
wire  signed [11:0] sext_ln1513_1_fu_1519_p1;
wire   [0:0] tmp_17_fu_1474_p3;
wire   [12:0] sub_ln1513_2_fu_1504_p2;
wire   [12:0] zext_ln1513_1_fu_1523_p1;
wire   [11:0] sub_ln1513_3_fu_1546_p2;
wire   [10:0] trunc_ln1513_1_i_fu_1551_p4;
wire  signed [11:0] sext_ln1513_2_fu_1561_p1;
wire   [12:0] zext_ln1513_2_fu_1565_p1;
wire   [10:0] trunc_ln1513_5_i_fu_1575_p4;
wire  signed [11:0] sext_ln1513_3_fu_1584_p1;
wire   [0:0] tmp_18_fu_1539_p3;
wire   [12:0] sub_ln1513_4_fu_1569_p2;
wire   [12:0] zext_ln1513_3_fu_1588_p1;
wire   [0:0] icmp_ln1027_fu_1468_p2;
wire   [12:0] ret_V_39_fu_1527_p3;
wire   [12:0] select_ln1027_fu_1600_p3;
wire   [13:0] zext_ln1496_21_fu_1535_p1;
wire  signed [13:0] sext_ln1027_fu_1607_p1;
wire   [12:0] ret_V_43_fu_1592_p3;
wire   [12:0] select_ln1027_1_fu_1617_p3;
wire  signed [13:0] sext_ln1027_1_fu_1624_p1;
wire   [0:0] tmp_23_fu_1652_p3;
wire   [0:0] xor_ln969_2_fu_1670_p2;
wire   [0:0] xor_ln997_fu_1692_p2;
wire   [0:0] icmp_ln997_fu_1687_p2;
wire   [0:0] or_ln997_fu_1705_p2;
wire   [9:0] select_ln997_fu_1697_p3;
wire   [9:0] trunc_ln963_1_fu_1684_p1;
wire   [9:0] r_3_fu_1710_p3;
wire   [0:0] icmp_ln998_fu_1718_p2;
wire   [9:0] trunc_ln963_fu_1681_p1;
wire   [0:0] or_ln998_fu_1737_p2;
wire   [9:0] select_ln998_fu_1730_p3;
wire   [9:0] select_ln998_1_fu_1741_p3;
wire   [9:0] r_4_fu_1723_p3;
wire   [9:0] b_3_fu_1749_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op67_load_state1;
reg    ap_enable_operation_67;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op78_load_state2;
reg    ap_enable_operation_78;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op88_store_state2;
reg    ap_enable_operation_88;
reg    ap_predicate_op82_load_state2;
reg    ap_enable_operation_82;
reg    ap_predicate_op106_load_state3;
reg    ap_enable_operation_106;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op129_store_state3;
reg    ap_enable_operation_129;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_58;
reg    ap_condition_448;
reg    ap_condition_445;
reg    ap_condition_1352;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

design_1_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_445)) begin
        if ((1'b1 == ap_condition_448)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367 <= {{lineBuffer_val_V_i_q1[29:20]}};
        end else if ((1'b1 == ap_condition_58)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367 <= {{imgRB_dout[29:20]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367 <= ap_phi_reg_pp0_iter1_p_0_0_01244_22367_ph_i_reg_367;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_445)) begin
        if ((1'b1 == ap_condition_448)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376 <= {{lineBuffer_val_V_i_q1[19:10]}};
        end else if ((1'b1 == ap_condition_58)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376 <= {{imgRB_dout[19:10]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376 <= ap_phi_reg_pp0_iter1_p_0_0_01245_22365_ph_i_reg_376;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_445)) begin
        if ((1'b1 == ap_condition_448)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385 <= trunc_ln628_fu_658_p1;
        end else if ((1'b1 == ap_condition_58)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385 <= trunc_ln868_fu_682_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385 <= ap_phi_reg_pp0_iter1_p_0_0_01246_22363_ph_i_reg_385;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_133_reg_496 <= pixWindow_val_val_V_91_fu_194;
        end else if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_133_reg_496 <= pixWindow_val_val_V_109_fu_808_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_133_reg_496 <= ap_phi_reg_pp0_iter2_pixWindow_val_val_V_133_reg_496;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_134_reg_487 <= pixWindow_val_val_V_92_fu_198;
        end else if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_134_reg_487 <= pixWindow_val_val_V_110_fu_802_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_134_reg_487 <= ap_phi_reg_pp0_iter2_pixWindow_val_val_V_134_reg_487;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_135_reg_478 <= pixWindow_val_val_V_93_fu_202;
        end else if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_135_reg_478 <= pixWindow_val_val_V_111_fu_796_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_pixWindow_val_val_V_135_reg_478 <= ap_phi_reg_pp0_iter2_pixWindow_val_val_V_135_reg_478;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_136_reg_441 <= pixWindow_val_val_V_85_fu_170;
        end else if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_136_reg_441 <= pixWindow_val_val_V_112_fu_789_p3;
        end else if (~(icmp_ln836_reg_1933_pp0_iter1_reg == 1'd1)) begin
            pixWindow_val_val_V_136_reg_441 <= ap_phi_reg_pp0_iter2_pixWindow_val_val_V_136_reg_441;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_137_reg_431 <= pixWindow_val_val_V_86_fu_174;
        end else if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_137_reg_431 <= pixWindow_val_val_V_113_fu_782_p3;
        end else if (~(icmp_ln836_reg_1933_pp0_iter1_reg == 1'd1)) begin
            pixWindow_val_val_V_137_reg_431 <= ap_phi_reg_pp0_iter2_pixWindow_val_val_V_137_reg_431;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_138_reg_421 <= pixWindow_val_val_V_87_fu_178;
        end else if (((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_138_reg_421 <= pixWindow_val_val_V_114_fu_775_p3;
        end else if (~(icmp_ln836_reg_1933_pp0_iter1_reg == 1'd1)) begin
            pixWindow_val_val_V_138_reg_421 <= ap_phi_reg_pp0_iter2_pixWindow_val_val_V_138_reg_421;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_83_fu_162 <= pixWindow_val_val_V_69_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_83_fu_162 <= {{lineBuffer_val_V_2_i_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_84_fu_166 <= pixWindow_val_val_V_70_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_84_fu_166 <= {{lineBuffer_val_V_2_i_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_85_fu_170 <= pixWindow_val_val_V_74_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_85_fu_170 <= trunc_ln628_reg_1980;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_86_fu_174 <= pixWindow_val_val_V_75_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_86_fu_174 <= tmp_i_reg_1989;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_87_fu_178 <= pixWindow_val_val_V_76_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_87_fu_178 <= tmp_2_i_reg_1998;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_88_fu_182 <= pixWindow_val_val_V_77_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_88_fu_182 <= ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_89_fu_186 <= pixWindow_val_val_V_78_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_89_fu_186 <= ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_90_fu_190 <= pixWindow_val_val_V_79_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_90_fu_190 <= ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_91_fu_194 <= pixWindow_val_val_V_71_i;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_91_fu_194 <= ap_phi_mux_pixWindow_val_val_V_136_phi_fu_444_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_92_fu_198 <= pixWindow_val_val_V_72_i;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_92_fu_198 <= ap_phi_mux_pixWindow_val_val_V_137_phi_fu_434_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_93_fu_202 <= pixWindow_val_val_V_73_i;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
            pixWindow_val_val_V_93_fu_202 <= ap_phi_mux_pixWindow_val_val_V_138_phi_fu_424_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            pixWindow_val_val_V_fu_158 <= pixWindow_val_val_V_i;
        end else if ((1'b1 == ap_condition_1352)) begin
            pixWindow_val_val_V_fu_158 <= trunc_ln628_2_fu_751_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln836_fu_577_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            x_fu_154 <= x_8_fu_583_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_154 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln998_reg_2231 <= and_ln998_fu_1675_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln836_reg_1933_pp0_iter2_reg <= icmp_ln836_reg_1933_pp0_iter1_reg;
        icmp_ln836_reg_1933_pp0_iter3_reg <= icmp_ln836_reg_1933_pp0_iter2_reg;
        icmp_ln969_reg_1969_pp0_iter2_reg <= icmp_ln969_reg_1969_pp0_iter1_reg;
        icmp_ln969_reg_1969_pp0_iter3_reg <= icmp_ln969_reg_1969_pp0_iter2_reg;
        icmp_ln969_reg_1969_pp0_iter4_reg <= icmp_ln969_reg_1969_pp0_iter3_reg;
        pixWindow_val_val_V_100_reg_2037_pp0_iter3_reg <= pixWindow_val_val_V_100_reg_2037;
        pixWindow_val_val_V_101_reg_2042_pp0_iter3_reg <= pixWindow_val_val_V_101_reg_2042;
        pixWindow_val_val_V_102_reg_2047_pp0_iter3_reg <= pixWindow_val_val_V_102_reg_2047;
        pixWindow_val_val_V_103_reg_2052_pp0_iter3_reg <= pixWindow_val_val_V_103_reg_2052;
        pixWindow_val_val_V_104_reg_2057_pp0_iter3_reg <= pixWindow_val_val_V_104_reg_2057;
        pixWindow_val_val_V_105_reg_2062_pp0_iter3_reg <= pixWindow_val_val_V_105_reg_2062;
        pixWindow_val_val_V_136_reg_441_pp0_iter3_reg <= pixWindow_val_val_V_136_reg_441;
        pixWindow_val_val_V_136_reg_441_pp0_iter4_reg <= pixWindow_val_val_V_136_reg_441_pp0_iter3_reg;
        pixWindow_val_val_V_137_reg_431_pp0_iter3_reg <= pixWindow_val_val_V_137_reg_431;
        pixWindow_val_val_V_137_reg_431_pp0_iter4_reg <= pixWindow_val_val_V_137_reg_431_pp0_iter3_reg;
        pixWindow_val_val_V_138_reg_421_pp0_iter3_reg <= pixWindow_val_val_V_138_reg_421;
        pixWindow_val_val_V_138_reg_421_pp0_iter4_reg <= pixWindow_val_val_V_138_reg_421_pp0_iter3_reg;
        pixWindow_val_val_V_94_reg_2022_pp0_iter3_reg <= pixWindow_val_val_V_94_reg_2022;
        pixWindow_val_val_V_95_reg_2027_pp0_iter3_reg <= pixWindow_val_val_V_95_reg_2027;
        pixWindow_val_val_V_96_reg_2032_pp0_iter3_reg <= pixWindow_val_val_V_96_reg_2032;
        pixWindow_val_val_V_97_reg_2067_pp0_iter3_reg <= pixWindow_val_val_V_97_reg_2067;
        pixWindow_val_val_V_98_reg_2073_pp0_iter3_reg <= pixWindow_val_val_V_98_reg_2073;
        pixWindow_val_val_V_99_reg_2079_pp0_iter3_reg <= pixWindow_val_val_V_99_reg_2079;
        ret_V_30_reg_2151 <= ret_V_30_fu_1163_p2;
        ret_V_31_reg_2120_pp0_iter3_reg <= ret_V_31_reg_2120;
        ret_V_42_reg_2188 <= ret_V_42_fu_1258_p2;
        ret_V_51_reg_2200 <= ret_V_51_fu_1408_p3;
        ret_V_54_reg_2171 <= ret_V_54_fu_1192_p2;
        ret_V_55_reg_2176 <= ret_V_55_fu_1206_p2;
        ret_V_65_reg_2210 <= ret_V_65_fu_1628_p2;
        sub_ln61_7_reg_2161 <= sub_ln61_7_fu_1173_p2;
        sub_ln61_8_reg_2166 <= sub_ln61_8_fu_1179_p2;
        tmp_24_reg_2226 <= {{ret_V_65_fu_1628_p2[13:10]}};
        tmp_25_reg_1976_pp0_iter2_reg <= tmp_25_reg_1976_pp0_iter1_reg;
        tmp_25_reg_1976_pp0_iter3_reg <= tmp_25_reg_1976_pp0_iter2_reg;
        tmp_25_reg_1976_pp0_iter4_reg <= tmp_25_reg_1976_pp0_iter3_reg;
        trunc_ln61_7_reg_2156 <= trunc_ln61_7_fu_1169_p1;
        trunc_ln61_8_reg_2125_pp0_iter3_reg <= trunc_ln61_8_reg_2125;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp162_i_reg_1953_pp0_iter1_reg <= cmp162_i_reg_1953;
        icmp_ln836_reg_1933 <= icmp_ln836_fu_577_p2;
        icmp_ln836_reg_1933_pp0_iter1_reg <= icmp_ln836_reg_1933;
        icmp_ln846_reg_1937_pp0_iter1_reg <= icmp_ln846_reg_1937;
        icmp_ln969_reg_1969_pp0_iter1_reg <= icmp_ln969_reg_1969;
        lineBuffer_val_V_2_i_addr_reg_1947_pp0_iter1_reg <= lineBuffer_val_V_2_i_addr_reg_1947;
        tmp_25_reg_1976_pp0_iter1_reg <= tmp_25_reg_1976;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_0_0_01244_22367_ph_i_reg_367 <= ap_phi_reg_pp0_iter0_p_0_0_01244_22367_ph_i_reg_367;
        ap_phi_reg_pp0_iter1_p_0_0_01245_22365_ph_i_reg_376 <= ap_phi_reg_pp0_iter0_p_0_0_01245_22365_ph_i_reg_376;
        ap_phi_reg_pp0_iter1_p_0_0_01246_22363_ph_i_reg_385 <= ap_phi_reg_pp0_iter0_p_0_0_01246_22363_ph_i_reg_385;
        ap_phi_reg_pp0_iter1_pixWindow_val_val_V_133_reg_496 <= ap_phi_reg_pp0_iter0_pixWindow_val_val_V_133_reg_496;
        ap_phi_reg_pp0_iter1_pixWindow_val_val_V_134_reg_487 <= ap_phi_reg_pp0_iter0_pixWindow_val_val_V_134_reg_487;
        ap_phi_reg_pp0_iter1_pixWindow_val_val_V_135_reg_478 <= ap_phi_reg_pp0_iter0_pixWindow_val_val_V_135_reg_478;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pixWindow_val_val_V_133_reg_496 <= ap_phi_reg_pp0_iter1_pixWindow_val_val_V_133_reg_496;
        ap_phi_reg_pp0_iter2_pixWindow_val_val_V_134_reg_487 <= ap_phi_reg_pp0_iter1_pixWindow_val_val_V_134_reg_487;
        ap_phi_reg_pp0_iter2_pixWindow_val_val_V_135_reg_478 <= ap_phi_reg_pp0_iter1_pixWindow_val_val_V_135_reg_478;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_577_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln846_fu_605_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp162_i_reg_1953 <= cmp162_i_fu_611_p2;
        lineBuffer_val_V_2_i_addr_reg_1947 <= zext_ln836_1_fu_589_p1;
        lineBuffer_val_V_i_addr_reg_1941 <= zext_ln836_1_fu_589_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln836_fu_577_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln846_reg_1937 <= icmp_ln846_fu_605_p2;
        icmp_ln969_reg_1969 <= icmp_ln969_fu_633_p2;
        tmp_25_reg_1976 <= or_ln1007_fu_639_p2[32'd11];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pixWindow_val_val_V_100_reg_2037 <= pixWindow_val_val_V_85_fu_170;
        pixWindow_val_val_V_101_reg_2042 <= pixWindow_val_val_V_86_fu_174;
        pixWindow_val_val_V_102_reg_2047 <= pixWindow_val_val_V_87_fu_178;
        pixWindow_val_val_V_103_reg_2052 <= pixWindow_val_val_V_88_fu_182;
        pixWindow_val_val_V_104_reg_2057 <= pixWindow_val_val_V_89_fu_186;
        pixWindow_val_val_V_105_reg_2062 <= pixWindow_val_val_V_90_fu_190;
        pixWindow_val_val_V_94_reg_2022 <= pixWindow_val_val_V_fu_158;
        pixWindow_val_val_V_95_reg_2027 <= pixWindow_val_val_V_83_fu_162;
        pixWindow_val_val_V_96_reg_2032 <= pixWindow_val_val_V_84_fu_166;
        pixWindow_val_val_V_97_reg_2067 <= pixWindow_val_val_V_91_fu_194;
        pixWindow_val_val_V_98_reg_2073 <= pixWindow_val_val_V_92_fu_198;
        pixWindow_val_val_V_99_reg_2079 <= pixWindow_val_val_V_93_fu_202;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
        ret_V_31_reg_2120 <= ret_V_31_fu_957_p2;
        ret_V_62_reg_2141 <= ret_V_62_fu_979_p2;
        ret_V_63_reg_2146 <= ret_V_63_fu_985_p2;
        trunc_ln61_8_reg_2125 <= trunc_ln61_8_fu_963_p1;
        zext_ln1496_11_reg_2100[9 : 0] <= zext_ln1496_11_fu_933_p1[9 : 0];
        zext_ln1496_12_reg_2105[9 : 0] <= zext_ln1496_12_fu_937_p1[9 : 0];
        zext_ln1496_15_reg_2110[9 : 0] <= zext_ln1496_15_fu_941_p1[9 : 0];
        zext_ln1496_16_reg_2115[9 : 0] <= zext_ln1496_16_fu_945_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln969_reg_1969_pp0_iter2_reg == 1'd0))) begin
        ret_V_38_reg_2181 <= ret_V_38_fu_1232_p2;
        ret_V_47_reg_2195 <= ret_V_47_fu_1332_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln969_reg_1969_pp0_iter1_reg == 1'd0) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
        ret_V_60_reg_2131 <= ret_V_60_fu_967_p2;
        ret_V_61_reg_2136 <= ret_V_61_fu_973_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln969_reg_1969_pp0_iter3_reg == 1'd0))) begin
        ret_V_64_reg_2205 <= ret_V_64_fu_1611_p2;
        tmp_21_reg_2215 <= ret_V_64_fu_1611_p2[32'd13];
        tmp_22_reg_2221 <= {{ret_V_64_fu_1611_p2[13:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_i_reg_1998 <= {{lineBuffer_val_V_i_q1[29:20]}};
        tmp_i_reg_1989 <= {{lineBuffer_val_V_i_q1[19:10]}};
        trunc_ln628_reg_1980 <= trunc_ln628_fu_658_p1;
    end
end

always @ (*) begin
    if (((icmp_ln836_fu_577_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_130_phi_fu_472_p4 = pixWindow_val_val_V_fu_158;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_130_phi_fu_472_p4 = pixWindow_val_val_V_106_fu_830_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_130_phi_fu_472_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_130_reg_469;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_130_phi_fu_472_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_130_reg_469;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_131_phi_fu_463_p4 = pixWindow_val_val_V_83_fu_162;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_131_phi_fu_463_p4 = pixWindow_val_val_V_107_fu_822_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_131_phi_fu_463_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_131_reg_460;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_131_phi_fu_463_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_131_reg_460;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_132_phi_fu_454_p4 = pixWindow_val_val_V_84_fu_166;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_132_phi_fu_454_p4 = pixWindow_val_val_V_108_fu_814_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_132_phi_fu_454_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_132_reg_451;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_132_phi_fu_454_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_132_reg_451;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_136_phi_fu_444_p4 = pixWindow_val_val_V_85_fu_170;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_136_phi_fu_444_p4 = pixWindow_val_val_V_112_fu_789_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_136_phi_fu_444_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_136_reg_441;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_136_phi_fu_444_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_136_reg_441;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_137_phi_fu_434_p4 = pixWindow_val_val_V_86_fu_174;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_137_phi_fu_434_p4 = pixWindow_val_val_V_113_fu_782_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_137_phi_fu_434_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_137_reg_431;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_137_phi_fu_434_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_137_reg_431;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_138_phi_fu_424_p4 = pixWindow_val_val_V_87_fu_178;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_138_phi_fu_424_p4 = pixWindow_val_val_V_114_fu_775_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_138_phi_fu_424_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_138_reg_421;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_138_phi_fu_424_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_138_reg_421;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_139_phi_fu_415_p4 = pixWindow_val_val_V_88_fu_182;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_139_phi_fu_415_p4 = pixWindow_val_val_V_115_fu_854_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_139_phi_fu_415_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_139_reg_412;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_139_phi_fu_415_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_139_reg_412;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_140_phi_fu_406_p4 = pixWindow_val_val_V_89_fu_186;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_140_phi_fu_406_p4 = pixWindow_val_val_V_116_fu_846_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_140_phi_fu_406_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_140_reg_403;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_140_phi_fu_406_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_140_reg_403;
    end
end

always @ (*) begin
    if ((icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0)) begin
        if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_pixWindow_val_val_V_141_phi_fu_397_p4 = pixWindow_val_val_V_90_fu_190;
        end else if ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_pixWindow_val_val_V_141_phi_fu_397_p4 = pixWindow_val_val_V_117_fu_838_p3;
        end else begin
            ap_phi_mux_pixWindow_val_val_V_141_phi_fu_397_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_141_reg_394;
        end
    end else begin
        ap_phi_mux_pixWindow_val_val_V_141_phi_fu_397_p4 = ap_phi_reg_pp0_iter2_pixWindow_val_val_V_141_reg_394;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_154;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op84_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_blk_n = imgRB_empty_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op84_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_read = 1'b1;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_25_reg_1976_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        imgRgb_blk_n = imgRgb_full_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_25_reg_1976_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        imgRgb_write = 1'b1;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_val_V_2_i_ce0 = 1'b1;
    end else begin
        lineBuffer_val_V_2_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_val_V_2_i_ce1 = 1'b1;
    end else begin
        lineBuffer_val_V_2_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0))) begin
        lineBuffer_val_V_2_i_we0 = 1'b1;
    end else begin
        lineBuffer_val_V_2_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_val_V_i_ce0 = 1'b1;
    end else begin
        lineBuffer_val_V_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_val_V_i_ce1 = 1'b1;
    end else begin
        lineBuffer_val_V_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (cmp60_i == 1'd1) & (icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_val_V_i_we0 = 1'b1;
    end else begin
        lineBuffer_val_V_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_80_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_80_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_81_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_81_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_82_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_82_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_83_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_83_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_84_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_84_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_85_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_85_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_86_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_86_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_87_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_87_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_88_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_88_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_89_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_89_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_90_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_90_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln836_reg_1933_pp0_iter3_reg == 1'd1))) begin
        pixWindow_val_val_V_91_i_out_ap_vld = 1'b1;
    end else begin
        pixWindow_val_val_V_91_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DBh_V_fu_1423_p3 = ((tmp_15_fu_1416_p3[0:0] == 1'b1) ? sub_ln61_7_reg_2161 : trunc_ln61_7_reg_2156);

assign DBv_V_fu_1436_p3 = ((tmp_16_fu_1429_p3[0:0] == 1'b1) ? sub_ln61_8_reg_2166 : trunc_ln61_8_reg_2125_pp0_iter3_reg);

assign DGh_V_fu_1117_p3 = ((tmp_13_fu_1109_p3[0:0] == 1'b1) ? sub_ln61_5_fu_1103_p2 : trunc_ln61_5_fu_1099_p1);

assign DGv_V_fu_1147_p3 = ((tmp_14_fu_1139_p3[0:0] == 1'b1) ? sub_ln61_6_fu_1133_p2 : trunc_ln61_6_fu_1129_p1);

assign DRh_V_fu_1047_p3 = ((tmp_fu_1039_p3[0:0] == 1'b1) ? sub_ln61_fu_1033_p2 : trunc_ln61_fu_1029_p1);

assign DRv_V_fu_1077_p3 = ((tmp_12_fu_1069_p3[0:0] == 1'b1) ? sub_ln61_4_fu_1063_p2 : trunc_ln61_4_fu_1059_p1);

assign PixBufVal_val_V_3_fu_868_p3 = ((cmp204_i[0:0] == 1'b1) ? tmp_i_reg_1989 : ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376);

assign PixBufVal_val_V_4_fu_862_p3 = ((cmp204_i[0:0] == 1'b1) ? tmp_2_i_reg_1998 : ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367);

assign PixBufVal_val_V_fu_874_p3 = ((cmp204_i[0:0] == 1'b1) ? trunc_ln628_reg_1980 : ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385);

assign and_ln998_fu_1675_p2 = (xor_ln969_2_fu_1670_p2 & tmp_23_fu_1652_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((tmp_25_reg_1976_pp0_iter4_reg == 1'd0) & (imgRgb_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_predicate_op84_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_25_reg_1976_pp0_iter4_reg == 1'd0) & (imgRgb_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_predicate_op84_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_25_reg_1976_pp0_iter4_reg == 1'd0) & (imgRgb_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_predicate_op84_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op84_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((tmp_25_reg_1976_pp0_iter4_reg == 1'd0) & (imgRgb_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1352 = ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_445 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_448 = ((cmp60_i_read_reg_1922 == 1'd0) & (icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0));
end

always @ (*) begin
    ap_condition_58 = ((cmp60_i == 1'd1) & (icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0));
end

always @ (*) begin
    ap_enable_operation_106 = (ap_predicate_op106_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_129 = (ap_predicate_op129_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_67 = (ap_predicate_op67_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_78 = (ap_predicate_op78_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_82 = (ap_predicate_op82_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_88 = (ap_predicate_op88_store_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_p_0_0_01244_22367_ph_i_reg_367 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_01245_22365_ph_i_reg_376 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_01246_22363_ph_i_reg_385 = 'bx;

assign ap_phi_reg_pp0_iter0_pixWindow_val_val_V_133_reg_496 = 'bx;

assign ap_phi_reg_pp0_iter0_pixWindow_val_val_V_134_reg_487 = 'bx;

assign ap_phi_reg_pp0_iter0_pixWindow_val_val_V_135_reg_478 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_130_reg_469 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_131_reg_460 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_132_reg_451 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_136_reg_441 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_137_reg_431 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_138_reg_421 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_139_reg_412 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_140_reg_403 = 'bx;

assign ap_phi_reg_pp0_iter2_pixWindow_val_val_V_141_reg_394 = 'bx;

always @ (*) begin
    ap_predicate_op106_load_state3 = ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op129_store_state3 = ((icmp_ln846_reg_1937_pp0_iter1_reg == 1'd1) & (icmp_ln836_reg_1933_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op67_load_state1 = ((icmp_ln836_fu_577_p2 == 1'd0) & (icmp_ln846_fu_605_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op78_load_state2 = ((icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0));
end

always @ (*) begin
    ap_predicate_op82_load_state2 = ((icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0));
end

always @ (*) begin
    ap_predicate_op84_read_state2 = ((cmp60_i == 1'd1) & (icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0));
end

always @ (*) begin
    ap_predicate_op88_store_state2 = ((cmp60_i == 1'd1) & (icmp_ln846_reg_1937 == 1'd1) & (icmp_ln836_reg_1933 == 1'd0));
end

assign b_3_fu_1749_p3 = ((or_ln998_fu_1737_p2[0:0] == 1'b1) ? select_ln998_fu_1730_p3 : select_ln998_1_fu_1741_p3);

assign cmp162_i_fu_611_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign cmp60_i_read_reg_1922 = cmp60_i;

assign icmp_ln1027_fu_1468_p2 = ((ret_V_33_fu_1449_p2 < ret_V_35_fu_1462_p2) ? 1'b1 : 1'b0);

assign icmp_ln836_fu_577_p2 = ((ap_sig_allocacmp_z == add_ln833_i) ? 1'b1 : 1'b0);

assign icmp_ln846_fu_605_p2 = ((ap_sig_allocacmp_z < trunc_ln) ? 1'b1 : 1'b0);

assign icmp_ln969_fu_633_p2 = ((xor_i == zext_ln969_fu_629_p1) ? 1'b1 : 1'b0);

assign icmp_ln997_fu_1687_p2 = (($signed(tmp_22_reg_2221) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln998_fu_1718_p2 = (($signed(tmp_24_reg_2226) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign imgRgb_din = {{{r_4_fu_1723_p3}, {b_3_fu_1749_p3}}, {pixWindow_val_val_V_137_reg_431_pp0_iter4_reg}};

assign lineBuffer_val_V_2_i_address0 = lineBuffer_val_V_2_i_addr_reg_1947_pp0_iter1_reg;

assign lineBuffer_val_V_2_i_address1 = lineBuffer_val_V_2_i_addr_reg_1947;

assign lineBuffer_val_V_2_i_d0 = {{{PixBufVal_val_V_4_fu_862_p3}, {PixBufVal_val_V_3_fu_868_p3}}, {PixBufVal_val_V_fu_874_p3}};

assign lineBuffer_val_V_i_address0 = lineBuffer_val_V_i_addr_reg_1941;

assign lineBuffer_val_V_i_address1 = zext_ln836_1_fu_589_p1;

assign lineBuffer_val_V_i_d0 = imgRB_dout;

assign or_ln1007_fu_639_p2 = (out_y_i | out_x_fu_599_p2);

assign or_ln997_fu_1705_p2 = (tmp_21_reg_2215 | icmp_ln997_fu_1687_p2);

assign or_ln998_fu_1737_p2 = (icmp_ln969_reg_1969_pp0_iter4_reg | and_ln998_reg_2231);

assign out_x_fu_599_p2 = ($signed(zext_ln836_fu_573_p1) + $signed(12'd4095));

assign pixWindow_val_val_V_106_fu_830_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? trunc_ln628_2_fu_751_p1 : pixWindow_val_val_V_fu_158);

assign pixWindow_val_val_V_107_fu_822_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? tmp_4_i_fu_755_p4 : pixWindow_val_val_V_83_fu_162);

assign pixWindow_val_val_V_108_fu_814_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? tmp_5_i_fu_765_p4 : pixWindow_val_val_V_84_fu_166);

assign pixWindow_val_val_V_109_fu_808_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? trunc_ln628_reg_1980 : pixWindow_val_val_V_91_fu_194);

assign pixWindow_val_val_V_110_fu_802_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? tmp_i_reg_1989 : pixWindow_val_val_V_92_fu_198);

assign pixWindow_val_val_V_111_fu_796_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? tmp_2_i_reg_1998 : pixWindow_val_val_V_93_fu_202);

assign pixWindow_val_val_V_112_fu_789_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? trunc_ln628_reg_1980 : pixWindow_val_val_V_85_fu_170);

assign pixWindow_val_val_V_113_fu_782_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? tmp_i_reg_1989 : pixWindow_val_val_V_86_fu_174);

assign pixWindow_val_val_V_114_fu_775_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? tmp_2_i_reg_1998 : pixWindow_val_val_V_87_fu_178);

assign pixWindow_val_val_V_115_fu_854_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_p_0_0_01246_22363_ph_i_reg_385 : pixWindow_val_val_V_88_fu_182);

assign pixWindow_val_val_V_116_fu_846_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_p_0_0_01245_22365_ph_i_reg_376 : pixWindow_val_val_V_89_fu_186);

assign pixWindow_val_val_V_117_fu_838_p3 = ((cmp162_i_reg_1953_pp0_iter1_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_p_0_0_01244_22367_ph_i_reg_367 : pixWindow_val_val_V_90_fu_190);

assign pixWindow_val_val_V_80_i_out = pixWindow_val_val_V_94_reg_2022_pp0_iter3_reg;

assign pixWindow_val_val_V_81_i_out = pixWindow_val_val_V_95_reg_2027_pp0_iter3_reg;

assign pixWindow_val_val_V_82_i_out = pixWindow_val_val_V_96_reg_2032_pp0_iter3_reg;

assign pixWindow_val_val_V_83_i_out = pixWindow_val_val_V_97_reg_2067_pp0_iter3_reg;

assign pixWindow_val_val_V_84_i_out = pixWindow_val_val_V_98_reg_2073_pp0_iter3_reg;

assign pixWindow_val_val_V_85_i_out = pixWindow_val_val_V_99_reg_2079_pp0_iter3_reg;

assign pixWindow_val_val_V_86_i_out = pixWindow_val_val_V_100_reg_2037_pp0_iter3_reg;

assign pixWindow_val_val_V_87_i_out = pixWindow_val_val_V_101_reg_2042_pp0_iter3_reg;

assign pixWindow_val_val_V_88_i_out = pixWindow_val_val_V_102_reg_2047_pp0_iter3_reg;

assign pixWindow_val_val_V_89_i_out = pixWindow_val_val_V_103_reg_2052_pp0_iter3_reg;

assign pixWindow_val_val_V_90_i_out = pixWindow_val_val_V_104_reg_2057_pp0_iter3_reg;

assign pixWindow_val_val_V_91_i_out = pixWindow_val_val_V_105_reg_2062_pp0_iter3_reg;

assign r_3_fu_1710_p3 = ((or_ln997_fu_1705_p2[0:0] == 1'b1) ? select_ln997_fu_1697_p3 : trunc_ln963_1_fu_1684_p1);

assign r_4_fu_1723_p3 = ((icmp_ln969_reg_1969_pp0_iter4_reg[0:0] == 1'b1) ? pixWindow_val_val_V_136_reg_441_pp0_iter4_reg : r_3_fu_1710_p3);

assign ret_V_27_fu_1055_p2 = (zext_ln1496_11_reg_2100 - zext_ln1496_12_reg_2105);

assign ret_V_28_fu_1093_p2 = (zext_ln1496_13_fu_1085_p1 - zext_ln1496_14_fu_1089_p1);

assign ret_V_29_fu_1125_p2 = (zext_ln1496_15_reg_2110 - zext_ln1496_16_reg_2115);

assign ret_V_30_fu_1163_p2 = (zext_ln1496_17_fu_1155_p1 - zext_ln1496_18_fu_1159_p1);

assign ret_V_31_fu_957_p2 = (zext_ln1496_19_fu_949_p1 - zext_ln1496_20_fu_953_p1);

assign ret_V_33_fu_1449_p2 = (zext_ln186_2_fu_1442_p1 + zext_ln186_3_fu_1445_p1);

assign ret_V_35_fu_1462_p2 = (zext_ln186_6_fu_1455_p1 + zext_ln186_7_fu_1458_p1);

assign ret_V_38_fu_1232_p2 = ($signed(sext_ln186_fu_1224_p1) + $signed(sext_ln186_1_fu_1228_p1));

assign ret_V_39_fu_1527_p3 = ((tmp_17_fu_1474_p3[0:0] == 1'b1) ? sub_ln1513_2_fu_1504_p2 : zext_ln1513_1_fu_1523_p1);

assign ret_V_42_fu_1258_p2 = ($signed(sext_ln186_2_fu_1250_p1) + $signed(sext_ln186_3_fu_1254_p1));

assign ret_V_43_fu_1592_p3 = ((tmp_18_fu_1539_p3[0:0] == 1'b1) ? sub_ln1513_4_fu_1569_p2 : zext_ln1513_3_fu_1588_p1);

assign ret_V_46_fu_1270_p2 = ($signed(sext_ln186_4_fu_1264_p1) + $signed(sext_ln186_5_fu_1267_p1));

assign ret_V_47_fu_1332_p3 = ((tmp_19_fu_1276_p3[0:0] == 1'b1) ? sub_ln1513_6_fu_1308_p2 : zext_ln1513_5_fu_1328_p1);

assign ret_V_50_fu_1346_p2 = ($signed(sext_ln186_6_fu_1340_p1) + $signed(sext_ln186_7_fu_1343_p1));

assign ret_V_51_fu_1408_p3 = ((tmp_20_fu_1352_p3[0:0] == 1'b1) ? sub_ln1513_8_fu_1384_p2 : zext_ln1513_7_fu_1404_p1);

assign ret_V_54_fu_1192_p2 = (zext_ln186_fu_1184_p1 + zext_ln186_1_fu_1188_p1);

assign ret_V_55_fu_1206_p2 = (zext_ln186_4_fu_1198_p1 + zext_ln186_5_fu_1202_p1);

assign ret_V_56_fu_1212_p2 = (zext_ln1496_13_fu_1085_p1 - zext_ln1496_fu_1015_p1);

assign ret_V_57_fu_1218_p2 = (zext_ln1496_14_fu_1089_p1 - zext_ln1496_10_fu_1019_p1);

assign ret_V_58_fu_1238_p2 = (zext_ln1496_13_fu_1085_p1 - zext_ln1496_17_fu_1155_p1);

assign ret_V_59_fu_1244_p2 = (zext_ln1496_14_fu_1089_p1 - zext_ln1496_18_fu_1159_p1);

assign ret_V_60_fu_967_p2 = (zext_ln1496_15_fu_941_p1 - zext_ln1496_11_fu_933_p1);

assign ret_V_61_fu_973_p2 = (zext_ln1496_16_fu_945_p1 - zext_ln1496_12_fu_937_p1);

assign ret_V_62_fu_979_p2 = (zext_ln1496_15_fu_941_p1 - zext_ln1496_19_fu_949_p1);

assign ret_V_63_fu_985_p2 = (zext_ln1496_16_fu_945_p1 - zext_ln1496_20_fu_953_p1);

assign ret_V_64_fu_1611_p2 = ($signed(zext_ln1496_21_fu_1535_p1) - $signed(sext_ln1027_fu_1607_p1));

assign ret_V_65_fu_1628_p2 = ($signed(zext_ln1496_21_fu_1535_p1) - $signed(sext_ln1027_1_fu_1624_p1));

assign ret_V_fu_1023_p2 = (zext_ln1496_fu_1015_p1 - zext_ln1496_10_fu_1019_p1);

assign select_ln1027_1_fu_1617_p3 = ((icmp_ln1027_fu_1468_p2[0:0] == 1'b1) ? ret_V_43_fu_1592_p3 : ret_V_51_reg_2200);

assign select_ln1027_fu_1600_p3 = ((icmp_ln1027_fu_1468_p2[0:0] == 1'b1) ? ret_V_39_fu_1527_p3 : ret_V_47_reg_2195);

assign select_ln997_fu_1697_p3 = ((xor_ln997_fu_1692_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln998_1_fu_1741_p3 = ((icmp_ln998_fu_1718_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln963_fu_1681_p1);

assign select_ln998_fu_1730_p3 = ((and_ln998_reg_2231[0:0] == 1'b1) ? 10'd0 : pixWindow_val_val_V_138_reg_421_pp0_iter4_reg);

assign sext_ln1027_1_fu_1624_p1 = $signed(select_ln1027_1_fu_1617_p3);

assign sext_ln1027_fu_1607_p1 = $signed(select_ln1027_fu_1600_p3);

assign sext_ln1513_1_fu_1519_p1 = $signed(trunc_ln1513_3_i_fu_1510_p4);

assign sext_ln1513_2_fu_1561_p1 = $signed(trunc_ln1513_1_i_fu_1551_p4);

assign sext_ln1513_3_fu_1584_p1 = $signed(trunc_ln1513_5_i_fu_1575_p4);

assign sext_ln1513_4_fu_1300_p1 = $signed(trunc_ln1513_2_i_fu_1290_p4);

assign sext_ln1513_5_fu_1324_p1 = $signed(trunc_ln1513_7_i_fu_1314_p4);

assign sext_ln1513_6_fu_1376_p1 = $signed(trunc_ln1513_10_i_fu_1366_p4);

assign sext_ln1513_7_fu_1400_p1 = $signed(trunc_ln1513_9_i_fu_1390_p4);

assign sext_ln1513_fu_1496_p1 = $signed(trunc_ln1513_i_fu_1486_p4);

assign sext_ln186_1_fu_1228_p1 = $signed(ret_V_57_fu_1218_p2);

assign sext_ln186_2_fu_1250_p1 = $signed(ret_V_58_fu_1238_p2);

assign sext_ln186_3_fu_1254_p1 = $signed(ret_V_59_fu_1244_p2);

assign sext_ln186_4_fu_1264_p1 = $signed(ret_V_60_reg_2131);

assign sext_ln186_5_fu_1267_p1 = $signed(ret_V_61_reg_2136);

assign sext_ln186_6_fu_1340_p1 = $signed(ret_V_62_reg_2141);

assign sext_ln186_7_fu_1343_p1 = $signed(ret_V_63_reg_2146);

assign sext_ln186_fu_1224_p1 = $signed(ret_V_56_fu_1212_p2);

assign sub_ln1513_2_fu_1504_p2 = (13'd0 - zext_ln1513_fu_1500_p1);

assign sub_ln1513_3_fu_1546_p2 = (12'd0 - ret_V_42_reg_2188);

assign sub_ln1513_4_fu_1569_p2 = (13'd0 - zext_ln1513_2_fu_1565_p1);

assign sub_ln1513_5_fu_1284_p2 = (12'd0 - ret_V_46_fu_1270_p2);

assign sub_ln1513_6_fu_1308_p2 = (13'd0 - zext_ln1513_4_fu_1304_p1);

assign sub_ln1513_7_fu_1360_p2 = (12'd0 - ret_V_50_fu_1346_p2);

assign sub_ln1513_8_fu_1384_p2 = (13'd0 - zext_ln1513_6_fu_1380_p1);

assign sub_ln1513_fu_1481_p2 = (12'd0 - ret_V_38_reg_2181);

assign sub_ln61_4_fu_1063_p2 = (10'd0 - trunc_ln61_4_fu_1059_p1);

assign sub_ln61_5_fu_1103_p2 = (10'd0 - trunc_ln61_5_fu_1099_p1);

assign sub_ln61_6_fu_1133_p2 = (10'd0 - trunc_ln61_6_fu_1129_p1);

assign sub_ln61_7_fu_1173_p2 = (10'd0 - trunc_ln61_7_fu_1169_p1);

assign sub_ln61_8_fu_1179_p2 = (10'd0 - trunc_ln61_8_reg_2125);

assign sub_ln61_fu_1033_p2 = (10'd0 - trunc_ln61_fu_1029_p1);

assign tmp_12_fu_1069_p3 = ret_V_27_fu_1055_p2[32'd10];

assign tmp_13_fu_1109_p3 = ret_V_28_fu_1093_p2[32'd10];

assign tmp_14_fu_1139_p3 = ret_V_29_fu_1125_p2[32'd10];

assign tmp_15_fu_1416_p3 = ret_V_30_reg_2151[32'd10];

assign tmp_16_fu_1429_p3 = ret_V_31_reg_2120_pp0_iter3_reg[32'd10];

assign tmp_17_fu_1474_p3 = ret_V_38_reg_2181[32'd11];

assign tmp_18_fu_1539_p3 = ret_V_42_reg_2188[32'd11];

assign tmp_19_fu_1276_p3 = ret_V_46_fu_1270_p2[32'd11];

assign tmp_20_fu_1352_p3 = ret_V_50_fu_1346_p2[32'd11];

assign tmp_23_fu_1652_p3 = ret_V_65_fu_1628_p2[32'd13];

assign tmp_4_i_fu_755_p4 = {{lineBuffer_val_V_2_i_q1[19:10]}};

assign tmp_5_i_fu_765_p4 = {{lineBuffer_val_V_2_i_q1[29:20]}};

assign tmp_fu_1039_p3 = ret_V_fu_1023_p2[32'd10];

assign trunc_ln1513_10_i_fu_1366_p4 = {{sub_ln1513_7_fu_1360_p2[11:1]}};

assign trunc_ln1513_1_i_fu_1551_p4 = {{sub_ln1513_3_fu_1546_p2[11:1]}};

assign trunc_ln1513_2_i_fu_1290_p4 = {{sub_ln1513_5_fu_1284_p2[11:1]}};

assign trunc_ln1513_3_i_fu_1510_p4 = {{ret_V_38_reg_2181[11:1]}};

assign trunc_ln1513_5_i_fu_1575_p4 = {{ret_V_42_reg_2188[11:1]}};

assign trunc_ln1513_7_i_fu_1314_p4 = {{ret_V_46_fu_1270_p2[11:1]}};

assign trunc_ln1513_9_i_fu_1390_p4 = {{ret_V_50_fu_1346_p2[11:1]}};

assign trunc_ln1513_i_fu_1486_p4 = {{sub_ln1513_fu_1481_p2[11:1]}};

assign trunc_ln61_4_fu_1059_p1 = ret_V_27_fu_1055_p2[9:0];

assign trunc_ln61_5_fu_1099_p1 = ret_V_28_fu_1093_p2[9:0];

assign trunc_ln61_6_fu_1129_p1 = ret_V_29_fu_1125_p2[9:0];

assign trunc_ln61_7_fu_1169_p1 = ret_V_30_fu_1163_p2[9:0];

assign trunc_ln61_8_fu_963_p1 = ret_V_31_fu_957_p2[9:0];

assign trunc_ln61_fu_1029_p1 = ret_V_fu_1023_p2[9:0];

assign trunc_ln628_2_fu_751_p1 = lineBuffer_val_V_2_i_q1[9:0];

assign trunc_ln628_fu_658_p1 = lineBuffer_val_V_i_q1[9:0];

assign trunc_ln844_fu_595_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln868_fu_682_p1 = imgRB_dout[9:0];

assign trunc_ln963_1_fu_1684_p1 = ret_V_64_reg_2205[9:0];

assign trunc_ln963_fu_1681_p1 = ret_V_65_reg_2210[9:0];

assign x_8_fu_583_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln969_1_fu_623_p2 = (xor_ln969_fu_617_p2 ^ 1'd1);

assign xor_ln969_2_fu_1670_p2 = (icmp_ln969_reg_1969_pp0_iter3_reg ^ 1'd1);

assign xor_ln969_fu_617_p2 = (x_phase_i ^ trunc_ln844_fu_595_p1);

assign xor_ln997_fu_1692_p2 = (tmp_21_reg_2215 ^ 1'd1);

assign zext_ln1496_10_fu_1019_p1 = pixWindow_val_val_V_85_fu_170;

assign zext_ln1496_11_fu_933_p1 = ap_phi_mux_pixWindow_val_val_V_130_phi_fu_472_p4;

assign zext_ln1496_12_fu_937_p1 = ap_phi_mux_pixWindow_val_val_V_139_phi_fu_415_p4;

assign zext_ln1496_13_fu_1085_p1 = ap_phi_reg_pp0_iter3_pixWindow_val_val_V_134_reg_487;

assign zext_ln1496_14_fu_1089_p1 = pixWindow_val_val_V_86_fu_174;

assign zext_ln1496_15_fu_941_p1 = ap_phi_mux_pixWindow_val_val_V_131_phi_fu_463_p4;

assign zext_ln1496_16_fu_945_p1 = ap_phi_mux_pixWindow_val_val_V_140_phi_fu_406_p4;

assign zext_ln1496_17_fu_1155_p1 = ap_phi_reg_pp0_iter3_pixWindow_val_val_V_135_reg_478;

assign zext_ln1496_18_fu_1159_p1 = pixWindow_val_val_V_87_fu_178;

assign zext_ln1496_19_fu_949_p1 = ap_phi_mux_pixWindow_val_val_V_132_phi_fu_454_p4;

assign zext_ln1496_20_fu_953_p1 = ap_phi_mux_pixWindow_val_val_V_141_phi_fu_397_p4;

assign zext_ln1496_21_fu_1535_p1 = pixWindow_val_val_V_137_reg_431_pp0_iter3_reg;

assign zext_ln1496_fu_1015_p1 = ap_phi_reg_pp0_iter3_pixWindow_val_val_V_133_reg_496;

assign zext_ln1513_1_fu_1523_p1 = $unsigned(sext_ln1513_1_fu_1519_p1);

assign zext_ln1513_2_fu_1565_p1 = $unsigned(sext_ln1513_2_fu_1561_p1);

assign zext_ln1513_3_fu_1588_p1 = $unsigned(sext_ln1513_3_fu_1584_p1);

assign zext_ln1513_4_fu_1304_p1 = $unsigned(sext_ln1513_4_fu_1300_p1);

assign zext_ln1513_5_fu_1328_p1 = $unsigned(sext_ln1513_5_fu_1324_p1);

assign zext_ln1513_6_fu_1380_p1 = $unsigned(sext_ln1513_6_fu_1376_p1);

assign zext_ln1513_7_fu_1404_p1 = $unsigned(sext_ln1513_7_fu_1400_p1);

assign zext_ln1513_fu_1500_p1 = $unsigned(sext_ln1513_fu_1496_p1);

assign zext_ln186_1_fu_1188_p1 = DGh_V_fu_1117_p3;

assign zext_ln186_2_fu_1442_p1 = ret_V_54_reg_2171;

assign zext_ln186_3_fu_1445_p1 = DBh_V_fu_1423_p3;

assign zext_ln186_4_fu_1198_p1 = DRv_V_fu_1077_p3;

assign zext_ln186_5_fu_1202_p1 = DGv_V_fu_1147_p3;

assign zext_ln186_6_fu_1455_p1 = ret_V_55_reg_2176;

assign zext_ln186_7_fu_1458_p1 = DBv_V_fu_1436_p3;

assign zext_ln186_fu_1184_p1 = DRh_V_fu_1047_p3;

assign zext_ln836_1_fu_589_p1 = x_8_fu_583_p2;

assign zext_ln836_fu_573_p1 = ap_sig_allocacmp_z;

assign zext_ln969_fu_629_p1 = xor_ln969_1_fu_623_p2;

always @ (posedge ap_clk) begin
    zext_ln1496_11_reg_2100[10] <= 1'b0;
    zext_ln1496_12_reg_2105[10] <= 1'b0;
    zext_ln1496_15_reg_2110[10] <= 1'b0;
    zext_ln1496_16_reg_2115[10] <= 1'b0;
end

endmodule //design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_836_2
