// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_DebayerG (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgBayer_dout,
        imgBayer_num_data_valid,
        imgBayer_fifo_cap,
        imgBayer_empty_n,
        imgBayer_read,
        imgG_din,
        imgG_num_data_valid,
        imgG_fifo_cap,
        imgG_full_n,
        imgG_write,
        height,
        width,
        p_read,
        bayerPhase_c9_din,
        bayerPhase_c9_num_data_valid,
        bayerPhase_c9_fifo_cap,
        bayerPhase_c9_full_n,
        bayerPhase_c9_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [9:0] imgBayer_dout;
input  [2:0] imgBayer_num_data_valid;
input  [2:0] imgBayer_fifo_cap;
input   imgBayer_empty_n;
output   imgBayer_read;
output  [29:0] imgG_din;
input  [1:0] imgG_num_data_valid;
input  [1:0] imgG_fifo_cap;
input   imgG_full_n;
output   imgG_write;
input  [15:0] height;
input  [15:0] width;
input  [15:0] p_read;
output  [15:0] bayerPhase_c9_din;
input  [1:0] bayerPhase_c9_num_data_valid;
input  [1:0] bayerPhase_c9_fifo_cap;
input   bayerPhase_c9_full_n;
output   bayerPhase_c9_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgBayer_read;
reg imgG_write;
reg bayerPhase_c9_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
wire   [16:0] zext_ln229_fu_266_p1;
reg   [16:0] zext_ln229_reg_552;
wire   [16:0] loopHeight_fu_270_p2;
reg   [16:0] loopHeight_reg_557;
wire   [0:0] x_phase_fu_280_p1;
reg   [0:0] x_phase_reg_562;
reg   [14:0] trunc_ln248_1_reg_567;
wire   [16:0] add_ln270_fu_294_p2;
reg   [16:0] add_ln270_reg_573;
reg   [16:0] y_7_reg_578;
wire    ap_CS_fsm_state2;
reg   [9:0] bayerWindow_val_V_load_reg_588;
wire   [0:0] icmp_ln270_fu_308_p2;
reg   [9:0] bayerWindow_val_V_1_load_reg_593;
reg   [9:0] bayerWindow_val_V_2_load_reg_598;
reg   [9:0] bayerWindow_val_V_3_load_reg_603;
reg   [9:0] bayerWindow_val_V_4_load_reg_608;
reg   [9:0] bayerWindow_val_V_5_load_reg_613;
reg   [9:0] bayerWindow_val_V_6_load_reg_618;
reg   [9:0] bayerWindow_val_V_7_load_reg_623;
reg   [9:0] bayerWindow_val_V_8_load_reg_628;
reg   [9:0] bayerWindow_val_V_9_load_reg_633;
reg   [9:0] bayerWindow_val_V_10_load_reg_638;
reg   [9:0] bayerWindow_val_V_11_load_reg_643;
reg   [9:0] bayerWindow_val_V_12_load_reg_648;
reg   [9:0] bayerWindow_val_V_13_load_reg_653;
reg   [9:0] bayerWindow_val_V_14_load_reg_658;
reg   [9:0] bayerWindow_val_V_15_load_reg_663;
reg   [9:0] bayerWindow_val_V_16_load_reg_668;
reg   [9:0] bayerWindow_val_V_17_load_reg_673;
reg   [9:0] bayerWindow_val_V_18_load_reg_678;
reg   [9:0] bayerWindow_val_V_19_load_reg_683;
wire   [0:0] cmp84_fu_379_p2;
reg   [0:0] cmp84_reg_688;
wire   [16:0] out_y_fu_392_p2;
reg   [16:0] out_y_reg_693;
wire    ap_CS_fsm_state3;
wire   [14:0] xor_fu_402_p2;
reg   [14:0] xor_reg_698;
wire   [0:0] cmp724_fu_408_p2;
reg   [0:0] cmp724_reg_703;
wire   [0:0] cmp170_fu_414_p2;
reg   [0:0] cmp170_reg_708;
wire   [9:0] linebuf_yuv_val_V_q1;
wire   [9:0] linebuf_yuv_val_V_1_q1;
wire   [9:0] linebuf_yuv_val_V_2_q1;
wire   [9:0] linebuf_yuv_val_V_3_q1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_idle;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_ready;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read;
wire   [29:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_din;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_we0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce1;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_we0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce1;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_we0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce1;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce0;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_we0;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_d0;
wire   [10:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address1;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce1;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_39_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_39_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_38_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_38_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_37_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_37_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_36_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_36_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_35_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_35_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_34_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_34_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_33_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_33_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_32_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_32_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_31_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_31_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_30_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_30_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_29_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_29_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_28_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_28_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_27_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_27_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_26_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_26_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_25_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_25_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_24_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_24_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_23_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_23_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_22_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_22_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_21_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_21_out_ap_vld;
wire   [9:0] grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_20_out;
wire    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_20_out_ap_vld;
reg    grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [9:0] bayerWindow_val_V_19_fu_156;
reg   [9:0] bayerWindow_val_V_18_fu_152;
reg   [9:0] bayerWindow_val_V_17_fu_148;
reg   [9:0] bayerWindow_val_V_16_fu_144;
reg   [9:0] bayerWindow_val_V_15_fu_140;
reg   [9:0] bayerWindow_val_V_14_fu_136;
reg   [9:0] bayerWindow_val_V_13_fu_132;
reg   [9:0] bayerWindow_val_V_12_fu_128;
reg   [9:0] bayerWindow_val_V_11_fu_124;
reg   [9:0] bayerWindow_val_V_10_fu_120;
reg   [9:0] bayerWindow_val_V_9_fu_116;
reg   [9:0] bayerWindow_val_V_8_fu_112;
reg   [9:0] bayerWindow_val_V_7_fu_108;
reg   [9:0] bayerWindow_val_V_6_fu_104;
reg   [9:0] bayerWindow_val_V_5_fu_100;
reg   [9:0] bayerWindow_val_V_4_fu_96;
reg   [9:0] bayerWindow_val_V_3_fu_92;
reg   [9:0] bayerWindow_val_V_2_fu_88;
reg   [9:0] bayerWindow_val_V_1_fu_84;
reg   [9:0] bayerWindow_val_V_fu_80;
reg   [16:0] y_fu_76;
wire   [16:0] y_8_fu_313_p2;
reg    ap_block_state1;
wire   [16:0] zext_ln238_fu_276_p1;
wire   [0:0] empty_133_fu_389_p1;
wire   [14:0] and261_cast_fu_398_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce1),
    .q1(linebuf_yuv_val_V_q1)
);

design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce1),
    .q1(linebuf_yuv_val_V_1_q1)
);

design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_val_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce1),
    .q1(linebuf_yuv_val_V_2_q1)
);

design_1_v_demosaic_0_0_DebayerG_linebuf_yuv_val_V_RAM_AUTO_1R1W #(
    .DataWidth( 10 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
linebuf_yuv_val_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address0),
    .ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce0),
    .we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_we0),
    .d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_d0),
    .address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address1),
    .ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce1),
    .q1(linebuf_yuv_val_V_3_q1)
);

design_1_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_273_4 grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start),
    .ap_done(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done),
    .ap_idle(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_idle),
    .ap_ready(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_ready),
    .imgBayer_dout(imgBayer_dout),
    .imgBayer_num_data_valid(imgBayer_num_data_valid),
    .imgBayer_fifo_cap(2'd0),
    .imgBayer_empty_n(imgBayer_empty_n),
    .imgBayer_read(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read),
    .imgG_din(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_din),
    .imgG_num_data_valid(2'd0),
    .imgG_fifo_cap(2'd0),
    .imgG_full_n(imgG_full_n),
    .imgG_write(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write),
    .bayerWindow_val_V_19(bayerWindow_val_V_19_load_reg_683),
    .bayerWindow_val_V_18(bayerWindow_val_V_18_load_reg_678),
    .bayerWindow_val_V_17(bayerWindow_val_V_17_load_reg_673),
    .bayerWindow_val_V_16(bayerWindow_val_V_16_load_reg_668),
    .bayerWindow_val_V_15(bayerWindow_val_V_15_load_reg_663),
    .bayerWindow_val_V_14(bayerWindow_val_V_14_load_reg_658),
    .bayerWindow_val_V_13(bayerWindow_val_V_13_load_reg_653),
    .bayerWindow_val_V_12(bayerWindow_val_V_12_load_reg_648),
    .bayerWindow_val_V_11(bayerWindow_val_V_11_load_reg_643),
    .bayerWindow_val_V_10(bayerWindow_val_V_10_load_reg_638),
    .bayerWindow_val_V_9(bayerWindow_val_V_9_load_reg_633),
    .bayerWindow_val_V_8(bayerWindow_val_V_8_load_reg_628),
    .bayerWindow_val_V_7(bayerWindow_val_V_7_load_reg_623),
    .bayerWindow_val_V_6(bayerWindow_val_V_6_load_reg_618),
    .bayerWindow_val_V_5(bayerWindow_val_V_5_load_reg_613),
    .bayerWindow_val_V_4(bayerWindow_val_V_4_load_reg_608),
    .bayerWindow_val_V_3(bayerWindow_val_V_3_load_reg_603),
    .bayerWindow_val_V_2(bayerWindow_val_V_2_load_reg_598),
    .bayerWindow_val_V_1(bayerWindow_val_V_1_load_reg_593),
    .bayerWindow_val_V(bayerWindow_val_V_load_reg_588),
    .add_ln270(add_ln270_reg_573),
    .x_phase(x_phase_reg_562),
    .xor_r(xor_reg_698),
    .cmp724(cmp724_reg_703),
    .out_y(out_y_reg_693),
    .linebuf_yuv_val_V_3_address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address0),
    .linebuf_yuv_val_V_3_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce0),
    .linebuf_yuv_val_V_3_we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_we0),
    .linebuf_yuv_val_V_3_d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_d0),
    .linebuf_yuv_val_V_3_address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_address1),
    .linebuf_yuv_val_V_3_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_3_ce1),
    .linebuf_yuv_val_V_3_q1(linebuf_yuv_val_V_3_q1),
    .linebuf_yuv_val_V_2_address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address0),
    .linebuf_yuv_val_V_2_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce0),
    .linebuf_yuv_val_V_2_we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_we0),
    .linebuf_yuv_val_V_2_d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_d0),
    .linebuf_yuv_val_V_2_address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_address1),
    .linebuf_yuv_val_V_2_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_2_ce1),
    .linebuf_yuv_val_V_2_q1(linebuf_yuv_val_V_2_q1),
    .linebuf_yuv_val_V_1_address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address0),
    .linebuf_yuv_val_V_1_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce0),
    .linebuf_yuv_val_V_1_we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_we0),
    .linebuf_yuv_val_V_1_d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_d0),
    .linebuf_yuv_val_V_1_address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_address1),
    .linebuf_yuv_val_V_1_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_1_ce1),
    .linebuf_yuv_val_V_1_q1(linebuf_yuv_val_V_1_q1),
    .linebuf_yuv_val_V_address0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address0),
    .linebuf_yuv_val_V_ce0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce0),
    .linebuf_yuv_val_V_we0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_we0),
    .linebuf_yuv_val_V_d0(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_d0),
    .linebuf_yuv_val_V_address1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_address1),
    .linebuf_yuv_val_V_ce1(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_linebuf_yuv_val_V_ce1),
    .linebuf_yuv_val_V_q1(linebuf_yuv_val_V_q1),
    .zext_ln238(width),
    .cmp170(cmp170_reg_708),
    .cmp84(cmp84_reg_688),
    .bayerWindow_val_V_39_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_39_out),
    .bayerWindow_val_V_39_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_39_out_ap_vld),
    .bayerWindow_val_V_38_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_38_out),
    .bayerWindow_val_V_38_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_38_out_ap_vld),
    .bayerWindow_val_V_37_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_37_out),
    .bayerWindow_val_V_37_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_37_out_ap_vld),
    .bayerWindow_val_V_36_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_36_out),
    .bayerWindow_val_V_36_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_36_out_ap_vld),
    .bayerWindow_val_V_35_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_35_out),
    .bayerWindow_val_V_35_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_35_out_ap_vld),
    .bayerWindow_val_V_34_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_34_out),
    .bayerWindow_val_V_34_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_34_out_ap_vld),
    .bayerWindow_val_V_33_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_33_out),
    .bayerWindow_val_V_33_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_33_out_ap_vld),
    .bayerWindow_val_V_32_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_32_out),
    .bayerWindow_val_V_32_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_32_out_ap_vld),
    .bayerWindow_val_V_31_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_31_out),
    .bayerWindow_val_V_31_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_31_out_ap_vld),
    .bayerWindow_val_V_30_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_30_out),
    .bayerWindow_val_V_30_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_30_out_ap_vld),
    .bayerWindow_val_V_29_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_29_out),
    .bayerWindow_val_V_29_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_29_out_ap_vld),
    .bayerWindow_val_V_28_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_28_out),
    .bayerWindow_val_V_28_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_28_out_ap_vld),
    .bayerWindow_val_V_27_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_27_out),
    .bayerWindow_val_V_27_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_27_out_ap_vld),
    .bayerWindow_val_V_26_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_26_out),
    .bayerWindow_val_V_26_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_26_out_ap_vld),
    .bayerWindow_val_V_25_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_25_out),
    .bayerWindow_val_V_25_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_25_out_ap_vld),
    .bayerWindow_val_V_24_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_24_out),
    .bayerWindow_val_V_24_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_24_out_ap_vld),
    .bayerWindow_val_V_23_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_23_out),
    .bayerWindow_val_V_23_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_23_out_ap_vld),
    .bayerWindow_val_V_22_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_22_out),
    .bayerWindow_val_V_22_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_22_out_ap_vld),
    .bayerWindow_val_V_21_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_21_out),
    .bayerWindow_val_V_21_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_21_out_ap_vld),
    .bayerWindow_val_V_20_out(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_20_out),
    .bayerWindow_val_V_20_out_ap_vld(grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_20_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln270_fu_308_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_ready == 1'b1)) begin
            grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_76 <= 17'd0;
    end else if (((icmp_ln270_fu_308_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_76 <= y_8_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln270_reg_573 <= add_ln270_fu_294_p2;
        loopHeight_reg_557 <= loopHeight_fu_270_p2;
        trunc_ln248_1_reg_567 <= {{p_read[15:1]}};
        x_phase_reg_562 <= x_phase_fu_280_p1;
        zext_ln229_reg_552[15 : 0] <= zext_ln229_fu_266_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_30_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_10_fu_120 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_30_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln270_fu_308_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        bayerWindow_val_V_10_load_reg_638 <= bayerWindow_val_V_10_fu_120;
        bayerWindow_val_V_11_load_reg_643 <= bayerWindow_val_V_11_fu_124;
        bayerWindow_val_V_12_load_reg_648 <= bayerWindow_val_V_12_fu_128;
        bayerWindow_val_V_13_load_reg_653 <= bayerWindow_val_V_13_fu_132;
        bayerWindow_val_V_14_load_reg_658 <= bayerWindow_val_V_14_fu_136;
        bayerWindow_val_V_15_load_reg_663 <= bayerWindow_val_V_15_fu_140;
        bayerWindow_val_V_16_load_reg_668 <= bayerWindow_val_V_16_fu_144;
        bayerWindow_val_V_17_load_reg_673 <= bayerWindow_val_V_17_fu_148;
        bayerWindow_val_V_18_load_reg_678 <= bayerWindow_val_V_18_fu_152;
        bayerWindow_val_V_19_load_reg_683 <= bayerWindow_val_V_19_fu_156;
        bayerWindow_val_V_1_load_reg_593 <= bayerWindow_val_V_1_fu_84;
        bayerWindow_val_V_2_load_reg_598 <= bayerWindow_val_V_2_fu_88;
        bayerWindow_val_V_3_load_reg_603 <= bayerWindow_val_V_3_fu_92;
        bayerWindow_val_V_4_load_reg_608 <= bayerWindow_val_V_4_fu_96;
        bayerWindow_val_V_5_load_reg_613 <= bayerWindow_val_V_5_fu_100;
        bayerWindow_val_V_6_load_reg_618 <= bayerWindow_val_V_6_fu_104;
        bayerWindow_val_V_7_load_reg_623 <= bayerWindow_val_V_7_fu_108;
        bayerWindow_val_V_8_load_reg_628 <= bayerWindow_val_V_8_fu_112;
        bayerWindow_val_V_9_load_reg_633 <= bayerWindow_val_V_9_fu_116;
        bayerWindow_val_V_load_reg_588 <= bayerWindow_val_V_fu_80;
        cmp84_reg_688 <= cmp84_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_31_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_11_fu_124 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_31_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_32_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_12_fu_128 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_32_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_33_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_13_fu_132 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_33_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_34_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_14_fu_136 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_34_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_35_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_15_fu_140 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_35_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_36_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_16_fu_144 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_36_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_37_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_17_fu_148 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_37_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_38_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_18_fu_152 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_38_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_39_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_19_fu_156 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_39_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_21_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_1_fu_84 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_21_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_22_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_2_fu_88 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_22_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_23_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_3_fu_92 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_23_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_24_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_4_fu_96 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_24_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_25_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_5_fu_100 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_25_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_26_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_6_fu_104 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_26_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_27_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_7_fu_108 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_27_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_28_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_8_fu_112 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_28_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_29_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_9_fu_116 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_29_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_20_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        bayerWindow_val_V_fu_80 <= grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_bayerWindow_val_V_20_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cmp170_reg_708 <= cmp170_fu_414_p2;
        cmp724_reg_703 <= cmp724_fu_408_p2;
        out_y_reg_693 <= out_y_fu_392_p2;
        xor_reg_698 <= xor_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_7_reg_578 <= y_fu_76;
    end
end

always @ (*) begin
    if (((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln270_fu_308_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_full_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_write = 1'b1;
    end else begin
        bayerPhase_c9_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgBayer_read = grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgBayer_read;
    end else begin
        imgBayer_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgG_write = grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_write;
    end else begin
        imgG_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln270_fu_308_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln270_fu_308_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln270_fu_294_p2 = (zext_ln238_fu_276_p1 + 17'd2);

assign and261_cast_fu_398_p1 = empty_133_fu_389_p1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_c9_full_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c9_din = p_read;

assign cmp170_fu_414_p2 = ((y_7_reg_578 != 17'd0) ? 1'b1 : 1'b0);

assign cmp724_fu_408_p2 = ((and261_cast_fu_398_p1 == trunc_ln248_1_reg_567) ? 1'b1 : 1'b0);

assign cmp84_fu_379_p2 = ((y_fu_76 < zext_ln229_reg_552) ? 1'b1 : 1'b0);

assign empty_133_fu_389_p1 = y_7_reg_578[0:0];

assign grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start = grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_ap_start_reg;

assign icmp_ln270_fu_308_p2 = ((y_fu_76 == loopHeight_reg_557) ? 1'b1 : 1'b0);

assign imgG_din = grp_DebayerG_Pipeline_VITIS_LOOP_273_4_fu_202_imgG_din;

assign loopHeight_fu_270_p2 = (zext_ln229_fu_266_p1 + 17'd2);

assign out_y_fu_392_p2 = ($signed(y_7_reg_578) + $signed(17'd131070));

assign start_out = real_start;

assign x_phase_fu_280_p1 = p_read[0:0];

assign xor_fu_402_p2 = (trunc_ln248_1_reg_567 ^ and261_cast_fu_398_p1);

assign y_8_fu_313_p2 = (y_fu_76 + 17'd1);

assign zext_ln229_fu_266_p1 = height;

assign zext_ln238_fu_276_p1 = width;

always @ (posedge ap_clk) begin
    zext_ln229_reg_552[16] <= 1'b0;
end

endmodule //design_1_v_demosaic_0_0_DebayerG
